pipeline: supervised_embeddings
language: de
policies:
- name: MemoizationPolicy
- name: KerasPolicy
- name: MappingPolicy
- name: EmbeddingPolicy
- name: FallbackPolicy
  fallback_action_name: action_default_fallback
